apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::842403311947:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-UI0HL70O1FGY
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::842403311947:role/UdacityFlaskDeployCBKubectlRole
      username: build 
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-28T09:54:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1402"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a4fe0504-5428-4689-8fee-132c09938d4a
